### ISSUE TITLE
....author clearly hates windows users 

### ISSUE THREAD

**Issue by BriceShatzer** [kkoppenhaver/wp-indesign-bridge#12]
attached 
![capture](https://cloud.githubusercontent.com/assets/3858622/21336452/11842908-c62b-11e6-81c4-2090738f1e74.PNG)

**Comment by zstepek** [comment]
Clearly lol

**Comment by kkoppenhaver** [comment]
@zstepek Meet one of my co-workers who's sitting next to me :P Needs a README update or a patch to make sure a text frame is selected before content is trying to be inserted.

**Comment by zstepek** [comment]
Figured as much. I wonder if you can tie into the text placement functionality and implement this hack? http://indesignsecrets.com/autoflow-text-when-pasting.php#

**Comment by kkoppenhaver** [comment]
Hmm maybe. I'll look into it.  Another option that may work for 1.0 is just stopping the user and throwing up a dialog letting them know that they haven't selected a text frame.

**Comment by zstepek** [comment]
The dialog is definitely MVP

**Comment by kkoppenhaver** [comment]
@BriceShatzer Just because the full commit message got cut off:

```Stop the user if they don't have a text frame selected when they run the script, closes #12 and all its snark``` ಠ_ಠ
